Module: LambdaSharp.Challenge.Bookmarker
Version: 1.0-DEV
Description: Bookmark Manager with URL shortener and preview features.
Items:

  - Resource: BookmarksTable
    Description: DynamoDB for storing all the bookmark data
    Type: AWS::DynamoDB::Table
    Allow: ReadWrite
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: ID
          AttributeType: S
      KeySchema:
        - AttributeName: ID
          KeyType: HASH

  - Function: ApiFunctions
    Description: TO-DO - update function description
    Memory: 256
    Timeout: 30
    Sources:

      - Api: POST:/bookmarks
        Invoke: AddBookmark

      # - Api: GET:/bookmarks
      #   Invoke: GetBookmarks

      # - Api: GET:/bookmarks/{id}
      #   Invoke: GetBookmark

      # - Api: DELETE:/bookmarks/{id}
      #   Invoke: DeleteBookmark

  - Variable: ApiUrl
    Description: API Gateway URL
    Scope: public
    Value: !Ref Module::RestApi::Url
